simplemooc/accounts/urls.py
#from django.contrib.auth import login
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts import views



app_name = 'accounts'

urlpatterns = [
	#^$ para urls vazias e ^ para indicar a proxima url

	url(r'^$', views.dashboard, name='dashboard'),
	url(r'^entrar/', LoginView.as_view(),  name='login'),
	url(r'^sair/', LogoutView.as_view(), name='logout'),
	url(r'^cadastrar_se', views.register, name='register'),
	url(r'^nova-senha', views.password_reset, name='password_reset'),
	url(r'^confirmar-nova-senha/(?P<key>[\w]+)/$', views.password_reset_confirm, name='password_reset_confirm'),
	url(r'^editar-senha', views.edit_password, name='edit_password'),
	url(r'^editar', views.edit, name='edit'),
	
	

	]

simplemooc/core/urls.py
#from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'core'

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^contato/', views.contact, name='contact')

	]

simplemooc/forum/urls.py
from django.conf.urls import url, include
from simplemooc.forum import views

app_name = 'Forum'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'tag/(?P<tag>[\w_-]+)/$', views.index, name='index_tagged'),
    url(r'respostas/(?P<pk>\d+)/correta/$', views.replay_correct, name='replay_correct'),
    url(r'respostas/(?P<pk>\d+)/correta/$', views.replay_incorrect, name='replay_incorrect'),
    url(r'(?P<slug>[\w_-]+)/$', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from simplemooc.core import views, urls
from simplemooc.courses import views, urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('simplemooc.core.urls', namespace='Core')),
    path('curso/', include('simplemooc.courses.urls', namespace='Courses')),
    path('conta/', include('simplemooc.accounts.urls', namespace='Accounts')),
    path('forum/', include('simplemooc.forum.urls', namespace='Forum')),
	
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse 

def home(request):
	return render(request, 'home.html')


def contact(request):

	return render(request, 'contact.html')

# Create your views here.

simplemooc/core/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma incrivel plataforma de ensino a distância" />
    <title>Conehcimento e Poder</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    
    <link rel="stylesheet" href='{% static "fontawesome/css/all.css" %}' />
    <link rel="stylesheet" href='{% static "css/styles.css" %}' />
</head>
<body>

<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
      
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home'%}">Início</a></li>
            <li><a href="{% url 'Courses:index'%}">Cursos</a></li>
            <li><a href="{% url 'Core:contact'%}">Contato</a></li>
            <li><a href="{% url 'Forum:index'%}">Forum</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'Accounts:dashboard'%}">Painel</a></li>
            <li><a href="{% url 'Accounts:logout'%}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'Accounts:login'%}">Logar</a></li>
            {% endif %}
        </ul>
    </div>    
</div>

    
<div class="content">
    {% if messages %}
    <aside class="info">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </aside>
    {% endif%}
    {% block content %} {% endblock %}   
    <div class="footer">
        Blog do Conehcimento - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

simplemooc/core/templates/contact.html
{% extends "base.html"%}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>

{% endblock %} 

simplemooc/core/templates/home.html
{% extends "base.html"%}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O Blog do Conehcimento visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Blog do Conehcimento tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Blog do Conehcimentovocê pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}