simplemooc/accounts/urls.py
#from django.contrib.auth import login
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts import views



app_name = 'accounts'

urlpatterns = [
	#^$ para urls vazias e ^ para indicar a proxima url

	url(r'^$', views.dashboard, name='dashboard'),
	url(r'^entrar/', LoginView.as_view(),  name='login'),
	url(r'^sair/', LogoutView.as_view(), name='logout'),
	url(r'^cadastrar_se', views.register, name='register'),
	url(r'^nova-senha', views.password_reset, name='password_reset'),
	url(r'^confirmar-nova-senha/(?P<key>[\w]+)/$', views.password_reset_confirm, name='password_reset_confirm'),
	url(r'^editar-senha', views.edit_password, name='edit_password'),
	url(r'^editar', views.edit, name='edit'),
	
	

	]

simplemooc/courses/urls.py
#from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'Courses'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	#url(r'^(?P<pk>\d+)/$', views.details, name='details')
	url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
	url(r'^(?P<slug>[\w_-]+)/inscricao$', views.enrollment, name='enrollment'),
	url(r'^(?P<slug>[\w_-]+)/cancelar-inscricao$', views.undo_enrollments, name='undo_enrollments'),
	url(r'^(?P<slug>[\w_-]+)/anuncios$', views.announcements, name='announcements'),
	url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', views.show_announcement, name='show_announcement'),
	url(r'^(?P<slug>[\w_-]+)/aulas$', views.lessons, name='lessons'),
	url(r'^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$', views.lesson, name='lesson'),
	url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', views.material, name='material'),
	
	
	

	]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from simplemooc.core import views, urls
from simplemooc.courses import views, urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('simplemooc.core.urls', namespace='Core')),
    path('curso/', include('simplemooc.courses.urls', namespace='Courses')),
    path('conta/', include('simplemooc.accounts.urls', namespace='Accounts')),
    path('forum/', include('simplemooc.forum.urls', namespace='Forum')),
	
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, UserManager, 
    PermissionsMixin)

from django.conf import settings 

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome do Usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
        'O Nome do usuario pode conter letras, numeros ou @ /. + - _', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_staff = models.BooleanField('É da Equipe?', blank=True, default=False)
    is_active = models.BooleanField('Esta Ativo?', blank=True, default=True)
    date_joined = models.DateTimeField('Data de  Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, 
        verbose_name = 'Usuario', related_name = 'resets'
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']    

simplemooc/accounts/forms.py
from django import forms 
from .models import PasswordReset
from simplemooc.core.utils import generate_hash_key
from simplemooc.core.mail import send_mail_template
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, password_validation
from django.shortcuts import render, redirect

User = get_user_model()


class PasswordResetForm(forms.Form):
    
    error_messages = {
        'password_mismatch': ('E-mail não cadastro!'),
    }

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            self.error_messages['password_mismatch']
            )

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar Nova senha '
        context = {
            'reset':reset,
        }
        send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):

    #mensagem de Error senha
    error_messages = {
        'password_mismatch': ('Senhas não são iguais.'),
    }

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                #Chamada var error mensagem
                self.error_messages['password_mismatch']
            )
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if commit:
            user.save()
        return user 

    class Meta:
        model = User
        fields = ['username',  'email']

class EditAccountForm(forms.ModelForm):

    
    class Meta:
        model = User
        fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (
    UserCreationForm, PasswordChangeForm, SetPasswordForm
)
from django.contrib.auth import (
    authenticate, login, get_user_model, password_validation
)
from django.conf import settings
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from .forms import EditAccountForm, PasswordResetForm
from .models import PasswordReset
from simplemooc.core.utils import generate_hash_key

from django.contrib import messages
from simplemooc.courses.models import Enrollment


User = get_user_model()

@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    
    return render(request, template_name, context)

def register(request):
    template_name = 'registration/register.html'
    if request.method ==  'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
                )
            login(request, user)    
            return redirect('core:home')

    else:
        form = RegisterForm()        
    context = {
        'form': form
    }
    return render(request, template_name, context)

def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form']=form 
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success']= True
    context['form']=form    
    return render(request, template_name, context)

def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method ==  'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)

            context['success'] = True

            messages.success(request, 'Dados Alterado com Sucesso!')
            return redirect('accounts:dashboard')

    else:
        form = EditAccountForm(instance=request.user)

    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user) 
        if form.is_valid():
            form.save()

            context['success'] = True

            messages.success(request, 'Senha Editada com Sucesso!')
            return redirect('accounts:dashboard')

    else:
        form = PasswordChangeForm(user=request.user)  
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}
{% load courses_tags %}
{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
   
    <div class="pure-u-1">
        
            {% block breadcrumb %}
            
                <li><a href="{% url 'accounts:dashboard' %}">Meu Painel </a></li>
            
            
            {% endblock %}
        
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            
            <ul>
                <l1 class="pure-menu-heading">
                    Bem Vindo, {{ user }}
                </l1>
                {% block extra_menu %} 
                
                <l1 class="pure-menu-heading">Meus Cursos</li>
                {%for enrollment in enrollments%}
                <li>
                    <a href="{% url 'Courses:announcements' enrollment.course.slug %}">
                        <i class="fas fa-book"></i>
                        {{ enrollment.course }}
                    </a>
                </li>
                {% empty %}
                <li>Se inscreva em um dos nossos Cursos</li>
                {% endfor %}
                <li class="pure-menu-heading">Minha Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                        <i class="far fa-edit"></i>
                        Editar Conta
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                        <i class="fas fa-user-lock"></i>
                        Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>Meus Cursos</h2>
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{ enrollment.course }}
                ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})
                </h3>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'Courses:announcements' enrollment.course.slug %}" class="pure-button button-error">Acessar</a>
                    <a href="{% url 'Courses:undo_enrollments' enrollment.course.slug %}" class="pure-button pure-button-primary">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nenhum curso inscrito</p>
            </aside>
            {% endfor%}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}
{% block breadcrumb %}
{{ block.super }}
    
    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>

{% endblock %}    
{% block dashboard_content %}

<form class="pure-form pure-form-starcked" method="POST">
    {% csrf_token %}
    {% if success %}
    <p>Os Dados foram alterdos com sucesso </p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>
       
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}
{% block breadcrumb %}
    {{ block.super }}
    
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
    
{% endblock %}    
{% block dashboard_content %}

<form class="pure-form pure-form-starcked" method="POST">
    {% csrf_token %}
    {% if success %}
    <p>Os Dados foram alterdos com sucesso </p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar</button>
        </div>
    </fieldset>
</form>
       
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
            <p> Um e-mail foi enviado para o seu e-mail</p>
        {% else %}
        <h2>Informe seu E-mail de  Cadastro</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                    
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
            
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
            <p> Senha Alterda com Sucesso</p>
        {% else %}
        <h2>Informe sua nova senha </h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                    
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Gravar</button>
                </div>
            </fieldset>
            
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p > Para cirar uma nova senha entre no Link: 
    <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key%}" title="Link Criar senha"Nova Senha></a>
</p>