simplemooc/core/urls.py
#from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'core'

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^contato/', views.contact, name='contact')

	]

simplemooc/forum/urls.py
from django.conf.urls import url, include
from simplemooc.forum import views

app_name = 'Forum'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'tag/(?P<tag>[\w_-]+)/$', views.index, name='index_tagged'),
    url(r'respostas/(?P<pk>\d+)/correta/$', views.replay_correct, name='replay_correct'),
    url(r'respostas/(?P<pk>\d+)/correta/$', views.replay_incorrect, name='replay_incorrect'),
    url(r'(?P<slug>[\w_-]+)/$', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from simplemooc.core import views, urls
from simplemooc.courses import views, urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('simplemooc.core.urls', namespace='Core')),
    path('curso/', include('simplemooc.courses.urls', namespace='Courses')),
    path('conta/', include('simplemooc.accounts.urls', namespace='Accounts')),
    path('forum/', include('simplemooc.forum.urls', namespace='Forum')),
	
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/forum/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager

from django.db.models.signals import pre_save
from django.urls import reverse


#Tabela comentarios
class Thread(models.Model):
    title = models.CharField('Titulo', max_length=100)
    slug = models.SlugField('Identificador', unique=True)
    body = models.TextField('Mensagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Autor', related_name='threads',
        on_delete=models.SET_NULL, null=True
    )

    views = models.IntegerField('Visualizacoes', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)

    tags = TaggableManager()
    
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em ', auto_now=True)    

    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse('Forum:thread', kwargs={'slug': self.slug })


    class Meta:
        verbose_name='Topico'
        verbose_name_plural = 'Topicos'
        ordering = ['-modified']    

      


class Replay(models.Model):
    thread = models.ForeignKey(
        Thread, verbose_name='Topico', related_name='replies', 
        on_delete=models.SET_NULL, null=True
    )
    replay = models.TextField('Mensagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Replay', related_name='replies',
        on_delete=models.SET_NULL, null=True
    )
    correct = models.BooleanField('Correta?', blank=True, default=False)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em ', auto_now=True)

    def __str__(self):
        return self.replay[:50]

   

    class Meta:
        verbose_name='Resposta'
        verbose_name_plural='Respostas'
        ordering=['-correct','created']

def post_save_replay(created, instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.replies.exclude(pk=instance.pk).update(
            correct=False
        )

def post_delete_replay(instance, **kwargs):
    instance.thread.answers=instance.thread.replies.count()
    instance.thread.save()

models.signals.post_save.connect(
    post_save_replay, sender=Replay, dispatch_uid='post_save_replay'
)    
models.signals.post_delete.connect(
    post_save_replay, sender=Replay, dispatch_uid='post_delete_replay'
)

simplemooc/forum/forms.py
from django import forms
from .models import Replay


class ReplayForm(forms.ModelForm):

    class Meta:
        model = Replay
        fields = ['replay']

simplemooc/forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from .models import Thread, Replay
from .forms import ReplayForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

#class ForumView(TemplateView):
    #template_name = 'forum/index.html'


class ForumView(ListView):
    
    paginate_by = 2
    template_name = 'forum/index.html'


    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')
        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order == 'answers':
            queryset = queryset.order_by('-answers')
        tag = self.kwargs.get('tag', '')
        if tag:
            queryset = queryset.filter(tags__slug__in=tag)    
        return queryset        

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context


class ThreadView(DetailView):
    queryset = Thread.objects.all()
    template_name = 'forum/thread.html'        

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if not self.request.user.is_authenticated or \
            (self.object.author != self.request.user):
            self.object.views = self.object.views + 1
            self.object.save()
        return response    

    def get_context_data(self, **kwargs):
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplayForm(self.request.POST or None)
        return context
    
    
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request, 'Para responder ao Topico precisa estar logado!!'
            )
            return redirect(self.request.path)
        
        
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            replay = form.save(commit=False)
            replay.thread = self.object
            replay.author = self.request.user
            
            replay.save()
            messages.success(self.request, 'Resposta Enviada com Sucesso ')
            context['form'] = ReplayForm()

        return self.render_to_response(context)    

class ReplayCorrectView(View):
    correct = True

    def get(self, request, pk):
        replay = get_object_or_404(Replay, pk=pk, thread__author=request.user)
        replay.correct = self.correct
        replay.save()
        messages.success(request, 'Resposta Atualizada')
        return redirect(replay.thread.get_absolute_url())

index = ForumView.as_view()   
thread = ThreadView.as_view() 
replay_correct = ReplayCorrectView.as_view()
replay_incorrect = ReplayCorrectView.as_view(correct=False)

simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <a href="{% url 'core:home' %}">Início</a>
        / <a href="{% url 'Forum:index' %}">Fórum de Discussões</a>
        
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="far fa-arrow-alt-circle-up"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                   
                    <a href="?order=answers">
                        <i class="fas fa-comment-medical"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'Forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}                    
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}
            <div class="well">
                <h3><a href="{{ thread.get_absolute_url }}" title="">{{ thread.title }}</a></h3>
                <h5>
                  Criado por {{ thread.author}} | {{ thread.answers }} 
                  resposta {{ thread.answers|pluralize }} | {{ thread.views}}
                  Visualiza {{ thread.views|pluralize:"çõe, ções"}} 
                   
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags:
                    {% for tag in thread.tags.all %}
                    <a href="{% url 'Forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last%}, {% endif %}
                    {% endfor %}
                    <a class="fright" href="{{ thread.get_absolute_url }}" title="">Atualizado a {{ thread.modified|timesince }} atrás</a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}
                <li> 
                    <a href="?page={{ page_obj.previous_page_number}}{% if request.GET.order %}&order={{ request.GET.order }}{% endif%}" title="">Anterior</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li {% if page == page_obj.number%} class="active" {% endif %}>
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif%}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li> 
                    <a href="?page={{ page_obj.next_page_number}}{% if request.GET.order %}&order={{ request.GET.order }}{% endif%}" title="">Proxima</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/forum/templates/forum/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <a href="{% url 'core:home' %}">Início</a>
        / <a href="{% url 'Forum:index' %}">Fórum de Discussões</a>
        / <a href="{{ object.get_absolute_url }}"> {{ object }}</a>

        </ul>
    
     </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="far fa-arrow-alt-circle-up"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                   
                    <a href="?order=answers">
                        <i class="fas fa-comment-medical"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'Forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}                    
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
          <div class="well">
              <h2>{{ object }}</h2>
              {{ object.body|linebreaks }}
              <h5>
                  Criado por {{ object.author }}
              </h5>
              <p>
                  <i class="fa fa-tags"></i>
                  {% for tag in object.tag.all %}
                  <a href="{% url 'Forum:index_tagged' tag.slug %}" title="">{{ tag }}</a> {% if not forloop.last %}, {% endif %}
                  {% endfor %}
                  <a class="fright" href="" title=""> Criado a {{ object.created|timesince }} atras</a>
              </p>
          </div>
            <div class="well" >
                <h4 id="comments">Respostas
                    <a class="fright" href="#add_comment">Responder</a>
                </h4>
                {% for replay in object.replies.all %}
                <hr />
                <p>
                    <strong>{{ replay.author }}</strong> disse a {{replay.created|timesince }} atras:
                    <br />
                    {{ replay.replay|linebreaksbr }}
                    <br />
                    {% if replay.correct %}
                        <br />
                        {% if replay.author == user %}
                        <a href="{% url 'Forum:replay_incorrect' replay.pk %}" title="" class="pure-button button-error">Cancelar Resposta Indicada</a>
                        {% endif %}
                        <span class="fright label-success">resposta recomendada pelo autor </span>
                    {% elif replay.author == user %} 
                        
                        <a href="{% url 'Forum:replay_correct' replay.pk %}" title="" class="pure-button button-success">Resposta Indicada</a>
                        <br />   
                    {% endif %}
                </p>
                {% endfor %}
                <hr />
            </div>
            <form method="POST", class="pure-form pure-form-stacked" id="add_comment">
                <fieldset>
                    {% csrf_token%}
                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock %}